create sequence alohandes_sequence;

CREATE TABLE PERSONANATURAL (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    CEDULA VARCHAR2(255 BYTE) NOT NULL,
    EDAD NUMBER NOT NULL,
    CONSTRAINT PERSONANATURAL_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE APARTAMENTO (
    ID NUMBER,
    UBICACION VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL, 
    PRECIOESPECIAL NUMBER NOT NULL,
    TAMANHIO NUMBER NOT NULL, 
    IDPERSONANATURAL NUMBER NOT NULL,
    AMOBLADO VARCHAR2(255 BYTE) NOT NULL,
    CONSTRAINT APARTAMENTO_PK PRIMARY KEY (ID)
);

CREATE TABLE COMUNIDAD (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    EDAD NUMBER NOT NULL,
    CONSTRAINT COMUNIDAD_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE EMPRESAHOTELERA (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    REGISTROCAMARA VARCHAR2(255 BYTE) NOT NULL,
    REGISTROSUPERINTENDENCIA VARCHAR2(255 BYTE) NOT NULL,
    CONSTRAINT EMPRESAHOTELERA_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE HABITACIONCOMPARTIDA (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    UBICACION VARCHAR2(255 BYTE) NOT NULL,
    TIPO VARCHAR2(255 BYTE) NOT NULL,
    IDEMPRESAHOTELERA NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    TAMANHIO NUMBER NOT NULL,
    HORARIOAPERTURA VARCHAR2(255 BYTE) NOT NULL,
    HORARIOCIERRE VARCHAR2(255 BYTE) NOT NULL, 
    CONSTRAINT HABITACIONCOMPARTIDA_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE HABITACIONVIVIENDA (
    ID NUMBER,
    UBICACION VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL,
    PRECIOESPECIAL NUMBER NOT NULL,
    TAMANHIO NUMBER NOT NULL,
    IDPERSONANATURAL NUMBER NOT NULL,
    CONSTRAINT HABITACIONVIVIENDA_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE HOTEL (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    UBICACION VARCHAR2(255 BYTE) NOT NULL,
    TIPOHABITACION VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL,
    TAMANHIO NUMBER NOT NULL,
    IDEMPRESAHOTELERA NUMBER NOT NULL,
    CONSTRAINT HOTEL_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE VIVIENDAPORDIA (
    ID NUMBER,
    UBICACION VARCHAR2(255 BYTE) NOT NULL,
    CARACTERISTICASVIVIENDA VARCHAR2(255 BYTE) NOT NULL,
    CARACTERISTICASSEGURO VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL,
    TAMANHIO NUMBER NOT NULL,
    IDCOMUNIDAD NUMBER NOT NULL,
    CONSTRAINT VIVIENDAPORDIA_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE VIVIENDAUNIVERSITARIA (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    REGISTROCAMARA VARCHAR2(255 BYTE) NOT NULL,
    REGISTROSUPERINTENDENCIA VARCHAR2(255 BYTE) NOT NULL,
    CONSTRAINT VIVIENDAUNIVERSITARIA_PK PRIMARY KEY (ID)
    );  
    
CREATE TABLE VIVIENDAPORSEMESTRE (
    ID NUMBER,
    UBICACION VARCHAR2(255 BYTE) NOT NULL,
    CAPACIDADHABITACION NUMBER NOT NULL,
    MENAJE VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL,
    TAMANHIO NUMBER NOT NULL,
    IDVIVIENDAUNIVERSITARIA NUMBER NOT NULL,
    CONSTRAINT VIVIENDAPORSEMESTRE_PK PRIMARY KEY (ID)
    ); 
    
CREATE TABLE USUARIO (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    CEDULA VARCHAR2(255 BYTE) NOT NULL,
    EDAD NUMBER NOT NULL,
    CELULAR VARCHAR2(255 BYTE) NOT NULL,
    VINCULACION VARCHAR2(255 BYTE) NOT NULL,
    CONSTRAINT USUARIO_PK PRIMARY KEY (ID)
    );      
    
CREATE TABLE RESERVA (
    ID NUMBER,
    FECHA VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL,
    IDALOHAMIENTO NUMBER,
    IDUSUARIO NUMBER,
    CONSTRAINT RESERVA_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE SERVICIO (
    ID NUMBER,
    NOMBRE VARCHAR2(255 BYTE) NOT NULL,
    DESCRIPCION VARCHAR2(255 BYTE) NOT NULL,
    PRECIO NUMBER NOT NULL,
    IDALOHAMIENTO NUMBER,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (ID)
    );

CREATE TABLE ALOHAMIENTO (
    ID NUMBER,
    IDAPARTAMENTO NUMBER,
    IDHABITACIONCOMPARTIDA NUMBER,
    IDHABITACIONVIVIENDA NUMBER,
    IDHOTEL NUMBER,
    IDVIVIENDAPORDIA NUMBER,
    IDVIVIENDAPORSEMESTRE NUMBER,
    CONSTRAINT ALOHAMIENTO_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE PROVEEDOR (
    ID NUMBER,
    IDCOMUNIAD NUMBER,
    IDEMPRESAHOTELERA NUMBER,
    IDPERSONANATURAL NUMBER,
    IDVIVIENDAUNIVERSITARIA NUMBER,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (ID)
    );
    
CREATE TABLE DINERORECIBIDO (
    DINERO NUMBER,
    ANHIO NUMBER,
    IDPROVEEDOR NUMBER,
    CONSTRAINT DINERO_PK PRIMARY KEY (DINERO)
    );
    
CREATE TABLE INDICEOCUPACION (
    INDICEOCUPACION NUMBER,
    IDALOHAMIENTO NUMBER,
    CONSTRAINT INDICE_PK PRIMARY KEY (INDICEOCUPACION)
    );
        
ALTER TABLE APARTAMENTO
ADD CONSTRAINT FK_P_PERSONANATURAL
    FOREIGN KEY (IDPERSONANATURAL)
    REFERENCES PERSONANATURAL(ID)
ENABLE;

ALTER TABLE APARTAMENTO
ADD CONSTRAINT CK_AMOBLADO
    CHECK(AMOBLADO IN('SI', 'NO'))
ENABLE;

ALTER TABLE HABITACIONCOMPARTIDA
ADD CONSTRAINT FK_H_EMPRESAHOTELERA
    FOREIGN KEY (IDEMPRESAHOTELERA)
    REFERENCES EMPRESAHOTELERA(ID)
ENABLE;

ALTER TABLE HABITACIONCOMPARTIDA
ADD CONSTRAINT CK_TIPO
    CHECK(TIPO IN('ESTANDAR', 'SEMISUITE', 'SUITE'))
ENABLE;

ALTER TABLE HABITACIONVIVIENDA
ADD CONSTRAINT FK_VI_PERSONANATURAL
    FOREIGN KEY (IDPERSONANATURAL)
    REFERENCES PERSONANATURAL(ID)
ENABLE;

ALTER TABLE HOTEL
ADD CONSTRAINT KF_H_EMPRESAHOTELERA
    FOREIGN KEY (IDEMPRESAHOTELERA)
    REFERENCES EMPRESAHOTELERA(ID)
ENABLE;

ALTER TABLE HOTEL
ADD CONSTRAINT CK_TIPOHABITACION
    CHECK(TIPOHABITACION IN('ESTANDAR', 'SEMISUITE', 'SUITE'))
ENABLE;

ALTER TABLE VIVIENDAPORDIA
ADD CONSTRAINT FK_VD_COMUNIDAD
    FOREIGN KEY (IDCOMUNIDAD)
    REFERENCES COMUNIDAD(ID)
ENABLE;

ALTER TABLE VIVIENDAPORSEMESTRE
ADD CONSTRAINT FK_VS_VIVIENDAUNIVERSITARIA
    FOREIGN KEY (IDVIVIENDAUNIVERSITARIA)
    REFERENCES VIVIENDAUNIVERSITARIA(ID)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RE_ALOHAMIENTO
    FOREIGN KEY (IDALOHAMIENTO)
    REFERENCES ALOHAMIENTO(ID)
ENABLE;

ALTER TABLE RESERVA
ADD CONSTRAINT FK_RE_USUARIO
    FOREIGN KEY(IDUSUARIO)
    REFERENCES USUARIO(ID)
ENABLE;

ALTER TABLE SERVICIO
ADD CONSTRAINT FK_SE_ALOHAMIENTO
    FOREIGN KEY(IDALOHAMIENTO)
    REFERENCES ALOHAMIENTO(ID)
ENABLE;

ALTER TABLE ALOHAMIENTO
ADD CONSTRAINT FK_AH_APARTAMENTO
    FOREIGN KEY (IDAPARTAMENTO)
    REFERENCES APARTAMENTO(ID)
ENABLE;

ALTER TABLE ALOHAMIENTO
ADD CONSTRAINT FK_AH_HABITACIONCOMPARTIDA
    FOREIGN KEY (IDHABITACIONCOMPARTIDA)
    REFERENCES HABITACIONCOMPARTIDA(ID)
ENABLE;

ALTER TABLE ALOHAMIENTO
ADD CONSTRAINT FK_AH_HABITACIONVIVIENDA
    FOREIGN KEY (IDHABITACIONVIVIENDA)
    REFERENCES HABITACIONVIVIENDA(ID)
ENABLE;

ALTER TABLE ALOHAMIENTO
ADD CONSTRAINT FK_AH_HOTEL
    FOREIGN KEY (IDHOTEL)
    REFERENCES HOTEL(ID)
ENABLE;

ALTER TABLE ALOHAMIENTO
ADD CONSTRAINT FK_AH_VIVIENDAPORDIA
    FOREIGN KEY (IDVIVIENDAPORDIA)
    REFERENCES VIVIENDAPORDIA(ID)
ENABLE;

ALTER TABLE ALOHAMIENTO
ADD CONSTRAINT FK_AH_VIVIENDAPORSEMESTRE
    FOREIGN KEY (IDVIVIENDAPORSEMESTRE)
    REFERENCES VIVIENDAPORSEMESTRE(ID)
ENABLE;

ALTER TABLE DINERORECIBIDO
ADD CONSTRAINT FK_DR_PROVEEDOR
    FOREIGN KEY (IDPROVEEDOR)
    REFERENCES PROVEEDOR(ID)
ENABLE;

ALTER TABLE INDICEOCUPACION
ADD CONSTRAINT FK_IO_ALOHAMIENTO
    FOREIGN KEY (IDALOHAMIENTO)
    REFERENCES ALOHAMIENTO(ID)
ENABLE;

COMMIT;
